photoblog/models.py
import pymysql
from photoblog import db
from werkzeug.security import generate_password_hash,check_password_hash
from datetime import datetime
from flask_login import UserMixin
from photoblog import login_manager

# The user_loader decorator allows flask-login to load the current user
# and grab their id.
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model,UserMixin):
    _tablename_="user"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    # This connects Photos to a User Author.
    # ONE To Many  User to Many Photos
    photo = db.relationship('Photo',backref='author',lazy='dynamic')

    def __init__(self, username, password, email):
        self.username = username
        self.password_hash = generate_password_hash(password)
        self.email = email

    def check_password(self,password):
        # https://stackoverflow.com/questions/23432478/flask-generate-password-hash-not-constant-output
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f"UserName: {self.username}"

class Photo(db.Model):
    _tablename_='photo'
    # Setup the relationship to the User table
    users = db.relationship(User)
    photo_id = db.Column(db.Integer, primary_key=True, autoincrement= True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    original = db.Column(db.String(200), nullable=False)
    thumbnail = db.Column(db.String(200), nullable=False)
    rotate = db.Column(db.String(200), nullable=False)
    sepia = db.Column(db.String(200), nullable=False)
    black_white = db.Column(db.String(200), nullable=False)


    def __init__(self, title, user_id, original, thumbnail, rotate, sepia, black_white):
        self.title = title
        self.user_id = user_id
        self.original = original
        self.thumbnail = thumbnail
        self.rotate = rotate
        self.sepia = sepia
        self.black_white = black_white

    def __repr__(self):
        return f"Post Id: {self.id} --- Date: {self.date} --- Title: {self.title}"


class aws(db.Model):
    _tablename_='aws'
    aws_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    auto_flag = db.Column(db.Integer, nullable=False)
    upper_threshold = db.Column(db.Float, nullable=False)
    lower_threshold = db.Column(db.Float, nullable=False)
    expand_ratio = db.Column(db.Integer, nullable=False)
    shrink_ratio = db.Column(db.Integer, nullable=False)

    def __init__(self, auto_flag, upper_threshold, lower_threshold, expand_ratio, shrink_ratio):
        self.auto_flag = auto_flag
        self.upper_threshold = upper_threshold
        self.lower_threshold = lower_threshold
        self.expand_ratio = expand_ratio
        self.shrink_ratio = shrink_ratio

    def __repr__(self):
        return f"Id: {self.aws_id}"

photoblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from photoblog.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password',
                             validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords Must Match!')])
    pass_confirm = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register!')

    def validate_email(self, field):
        # Check if not None for that user email!
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Your email has been registered already!')

    def validate_username(self, field):
        # Check if not None for that username!
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('Sorry, that username is taken!')

photoblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

#############################################################################
############ CONFIGURATIONS (CAN BE SEPARATE CONFIG.PY FILE) ###############
###########################################################################

app.config['SECRET_KEY'] = '123'


#################################
### DATABASE SETUPS ############
###############################
app.config['SQLALCHEMY_DATABASE_URI']='mysql+pymysql://root:ece1779pass@localhost:3306/ece1779'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True

db = SQLAlchemy(app)
Migrate(app,db)
###########################
#### LOGIN CONFIGS #######
#########################

login_manager = LoginManager()

# We can now pass in our app to the login manager
login_manager.init_app(app)

# Tell users what view to go to when they need to login.
login_manager.login_view = "users.login"


###########################
#### BLUEPRINT CONFIGS #######
#########################

from photoblog.users.user_util import users
#from photoblog.core.views import core
from photoblog.photos.upload import photos
from photoblog.photos.view import display
#db.create_all()


app.register_blueprint(users)
#app.register_blueprint(core)
app.register_blueprint(photos)
app.register_blueprint(display)

photoblog/users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required, login_manager
from photoblog import db
from photoblog.models import User
from photoblog.users.forms import LoginForm,RegistrationForm

users = Blueprint('users', __name__)

@users.route('/')
def index():
#This is the home page view.
    title = "PhotoBLog"
    return render_template('index.html',title = title)

@users.route('/register', methods=['GET', 'POST'])
def register():
    title = 'resigter'
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', title =title, form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    title = 'login'
    form = LoginForm()
    if form.validate_on_submit():
        # Grab the user from our User Models table
        user = User.query.filter_by(email=form.email.data).first()
        # Check that the user was supplied and the password is right
        # The verify_password method comes from the User object
        # https://stackoverflow.com/questions/2209755/python-operation-vs-is-not
        if user.check_password(form.password.data) and user is not None:
            # Log in the user
            login_user(user)
            flash('Logged in successfully.')
            return redirect(url_for('view.welcome'))
    return render_template('login.html', title=title,form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return "Logged Out"

@users.route('/test', methods=['GET', 'POST'])
@login_required
def test():
    return 'test'

photoblog/templates/base.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">
    <title>{{ title }}</title>
</head>
<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.login') }}">Log In</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.register') }}">Sign Up</a></li>
</ul>
<div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

photoblog/templates/complete.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>

        ul.nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .nav li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .nav .active {
            background-color: #4CAF50;
        }

        body {
            background-image: url("../static/background.jpeg");
            background-color: #cccccc;
        }
    </style>

</head>
<body>

<ul class="nav">
    <li style="float: left"><a href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
</ul>
<h1>
    <style>
        h1 {
            background-color: powderblue;
            color: blue;
            text-align: center;
            border: 3px solid green;
            padding: 60px;
            margin: 80px;
            line-height: 1.6em
        }

    </style>
    Upload Completed<br>

</h1>

</body>
</html>

photoblog/templates/display.html
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">

    <style>



        div.gallery {
            margin: 5px;
            border: 1px solid #ccc;
            float: left;
            width: 400px;
            height: auto;
        }

        div.gallery:hover {
            border: 1px solid #777;
        }

        div.gallery img {
            width: 100%;
            height: auto;
        }

        div.desc {
            padding: 15px;
            text-align: center;
            background-color: powderblue;
        }

        ul.nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .nav li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .nav .active {
            background-color: #4CAF50;
        }
        .nav .upload{
            background-color: #b8d16c;
        }


        body {

            background-color: #3dabe2;
        }

    </style>

    <title>{{ title }}</title>
</head>


<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
    <li style="float: right"><a class="username" style="background-color: teal">{{ user_name }}</a></li>
</ul>
<div>




    <br>
    <div class="photos">

        <div class="gallery">
            <img src="{{ image_list[0] }}" alt="Original">
            <div class="desc">Original</div>
        </div>

        <div class="gallery">
            <img src="{{ image_list[1] }}" alt="Rotation">
            <div class="desc">Rotation</div>
        </div>

        <div class="gallery">
            <img src="{{ image_list[2] }}" alt="Sepia">
            <div class="desc">Sepia</div>
        </div>

        <div class="gallery">
            <img src="{{ image_list[3] }}" alt="Black and White">
            <div class="desc">Black and White</div>
        </div>

    </div>
</div>
</body>
</html>

photoblog/templates/filenameerror.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>

        ul.nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .nav li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .nav .active {
            background-color: #4CAF50;
        }

        body {

            background-color: #3dabe2;
        }
    </style>

</head>
<body>

<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
</ul>
<h1>
    <style>
        h1 {
            background-color: powderblue;
            text-align: center;
            border: 3px solid green;
            padding: 60px;
            margin: 80px;
            line-height: 1.6em
        }

    </style>
    Filename not provided<br>

</h1>

</body>
</html>

photoblog/templates/home_page.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">

    <style>

        div.gallery {
            margin: 5px;
            border: 1px solid #ccc;
            float: left;
            width: 200px;
            height: 200px;
        }

        div.gallery img {
            width: 100%;
            height: 100%;
        }

        div.desc {
            padding: 15px;
            text-align: center;
            background-color: #CDC1C5;
        }
    </style>

    <title>{{ title }}</title>
</head>

<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('users.index') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
    <li style="float: right"><a class="username" style="background-color: teal">{{ user_name }}</a></li>
</ul>

<br>
<div class='photos'>
        {% for image in image_list %}
            <div>
                <div class="gallery">
                    <a href="../view/{{ title_list[loop.index-1][0] }}">
                        <img src="{{ image }}">
                    </a>
                </div>
            </div>
        {% endfor %}
</div>
</div>
</body>
</html>

photoblog/templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>
        <style>
            h1 {
                background-color: powderblue;

                text-align: center;
                border: 3px solid green;
                padding: 60px;
                margin: 80px;
                line-height: 1.6em
            }

        </style>
        This is the welcome page<br>
        If you are new to the website, please sign up<br>
        If you are old user, please log in
    </h1>

{% endblock %}

photoblog/templates/login.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>
        .custom-form {
            background-color: powderblue;
            text-align: center;
            margin-top: 100px;
            margin-bottom: 100px;
            margin-left: 500px;
            margin-right: 500px;
        }
    </style>

</head>
<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.login') }}">Log In</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.register') }}">Sign Up</a></li>
</ul>

<div class="custom-form">
    {% block content %}
        <form method="POST">
            {# This hidden_tag is a CSRF security feature. #}
            {{ form.hidden_tag() }}
            {{ form.username.label }} {{ form.username() }}<br>
            {{ form.password.label }} {{ form.password() }}<br>
            {{ form.submit() }}
        </form>
    {% endblock %}
</div>
</body>
</html>

photoblog/templates/logout.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">
    <title>{{ title }}</title>
</head>
<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.login') }}">Log In</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.register') }}">Sign Up</a></li>
</ul>
<h1>
    <style>
        h1 {
            background-color: powderblue;

            text-align: center;
            border: 3px solid green;
            padding: 60px;
            margin: 80px;
            line-height: 1.6em
        }

    </style>
    Logged Out<br>

</h1>

</body>
</html>

photoblog/templates/register.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>
        .custom-form{
            background-color: powderblue;
            text-align: center;
            margin-top: 100px;
            margin-bottom: 100px;
            margin-left: 500px;
            margin-right: 500px;
        }
    </style>

</head>
<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.login') }}">Log In</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.register') }}">Sign Up</a></li>
</ul>

<div class="custom-form">
    {% block content %}
        <form method="POST">
        {# This hidden_tag is a CSRF security feature. #}
        {{ form.hidden_tag() }}
        {{ form.email.label }} {{ form.email() }}<br>
        {{ form.username.label }} {{ form.username() }}<br>
        {{ form.password.label }} {{ form.password() }}<br>
        {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
        {{ form.submit() }}
        </form>
    {% endblock %}
</div>
</body>
</html>

photoblog/templates/typeerror.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>

        ul.nav {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: #333;
        }

        .nav li a {
            display: block;
            color: white;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
        }

        .nav .active {
            background-color: #4CAF50;
        }

        body {

            background-color: #3dabe2;
        }
    </style>

</head>
<body>

<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
</ul>
<h1>
    <style>
        h1 {
            background-color: powderblue;
            text-align: center;
            border: 3px solid green;
            padding: 60px;
            margin: 80px;
            line-height: 1.6em
        }

    </style>
    Upload File Type Error<br>

</h1>

</body>
</html>

photoblog/templates/upload.html
<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="./static/base.css">
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <style>
        .custom-form {
            background-color: powderblue;
            text-align: center;
            margin-top: 100px;
            margin-bottom: 100px;
            margin-left: 480px;
            margin-right: 480px;
        }
        .nav .active {
            background-color: #4CAF50;
        }

    </style>
</head>
<body>
<ul class="nav">
    <li style="float: left"><a class="active" href="{{ url_for('view.home_page') }}">Home</a></li>
    <li style="float: right"><a class="active" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li style="float: right"><a class="upload" href="{{ url_for('photos.test') }}">Upload</a></li>
</ul>
<div class="custom-form">
    <form action="/FileUpload" enctype="multipart/form-data" method="post">
        What is the image files to upload? <br/>
        <input type="file" name="uploadedfile"><br/>

        <input type="submit" value="Send">
        <input type="reset">
    </form>
</div>
</body>
</html>